apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rekor.fullname" . }}-mysql
  labels:
    app: {{ include "rekor.fullname" . }}-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "rekor.fullname" . }}-mysql
  template:
    metadata:
      labels:
        app: {{ include "rekor.fullname" . }}-mysql
    spec:
      containers:
        - name: mysql
          image: {{ .Values.mysql.image }}
          imagePullPolicy: {{ .Values.mysql.imagePullPolicy }}
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: {{ .Values.mysql.rootPassword }}
            - name: MYSQL_DATABASE
              value: {{ .Values.mysql.database }}
            - name: MYSQL_USER
              value: {{ .Values.mysql.username }}
            - name: MYSQL_PASSWORD
              value: {{ .Values.mysql.password }}
          ports:
            - containerPort: {{ .Values.mysql.service.port }}
          livenessProbe:
            exec:
              command: ["/bin/sh", "-c", "mysqladmin ping -u root -p${MYSQL_ROOT_PASSWORD}"]
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command: ["/bin/sh", "-c", "mysqladmin ping -u root -p${MYSQL_ROOT_PASSWORD}"]
            initialDelaySeconds: 5
            periodSeconds: 10
