apiVersion: v1
kind: Service
metadata:
  name: {{ include "rekor.fullname" . }}-redis
  labels:
    app: {{ include "rekor.fullname" . }}-redis
spec:
  ports:
    - port: {{ .Values.redis.service.port }}
      targetPort: {{ .Values.redis.service.port }}
      protocol: TCP
      name: redis
  selector:
    app: {{ include "rekor.fullname" . }}-redis
