apiVersion: v1
kind: Service
metadata:
  name: {{ include "rekor.fullname" . }}-trillian-log-signer
  labels:
    app: {{ include "rekor.fullname" . }}-trillian-log-signer
spec:
  ports:
    - port: {{ .Values.trillianLogSigner.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ include "rekor.fullname" . }}-trillian-log-signer
